# FROM ubuntu:18.04

# RUN apt-get -qq update
# RUN apt-get install -y --no-install-recommends \
#     python3-apt \
#     ca-certificates \
#     software-properties-common \ 
#     apt-transport-https \
#     gnupg-agent \
#     gnupg \
#     wget

# FROM ubuntu:18.04

# RUN apt-get -qq update
# RUN apt-get install -y --no-install-recommends \
#     python3-apt \
#     ca-certificates \
#     gnupg \
#     wget \
# && wget -O - https://yourserver.name/key/public 2>/dev/null | apt-key add -
